"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BrandMark } from "@/components/BrandMark";
import { cartTotal, formatETB } from "@/lib/currency";
import { copy, text } from "@/lib/i18n";
import type { CartLine, HotelService, Language, MenuCategory, MenuItem, TableInfo } from "@/lib/types";

type Props = { table: TableInfo; categories: MenuCategory[]; items: MenuItem[]; services: HotelService[] };
type View = "food" | "drink" | "lounge";

function LanguageToggle({ language, onChange }: { language: Language; onChange: (language: Language) => void }) {
  return <div className="flex rounded-full border border-[var(--line)] bg-white/80 p-1 text-xs font-bold"><button onClick={() => onChange("en")} className={`focus-ring rounded-full px-2.5 py-1.5 ${language === "en" ? "bg-[var(--ink)] text-white" : "text-[var(--muted)]"}`}>EN</button><button onClick={() => onChange("am")} className={`focus-ring font-am rounded-full px-2.5 py-1.5 ${language === "am" ? "bg-[var(--ink)] text-white" : "text-[var(--muted)]"}`}>አማ</button></div>;
}

function QuantityControl({ quantity, setQuantity }: { quantity: number; setQuantity: (value: number) => void }) {
  return <div className="flex items-center rounded-full border border-[var(--line)] bg-white"><button aria-label="Decrease quantity" className="focus-ring h-10 w-10 text-lg" onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button><span className="w-7 text-center text-sm font-bold">{quantity}</span><button aria-label="Increase quantity" className="focus-ring h-10 w-10 text-lg" onClick={() => setQuantity(Math.min(20, quantity + 1))}>+</button></div>;
}

export function TableMenu({ table, categories, items, services }: Props) {
  const [language, setLanguage] = useState<Language>("en");
  const [view, setView] = useState<View>("food");
  const [categoryId, setCategoryId] = useState<string | null>(null);
  const [selected, setSelected] = useState<MenuItem | null>(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [cart, setCart] = useState<CartLine[]>([]);
  const [service, setService] = useState<HotelService | null>(null);
  const [toast, setToast] = useState("");

  const storageKey = `fantish-cart-${table.token}`;
  useEffect(() => { const stored = window.localStorage.getItem(storageKey); if (stored) { try { setCart(JSON.parse(stored)); } catch { window.localStorage.removeItem(storageKey); } } }, [storageKey]);
  useEffect(() => { window.localStorage.setItem(storageKey, JSON.stringify(cart)); }, [cart, storageKey]);
  useEffect(() => { const available = categories.filter((c) => c.kind === view); if (!available.some((c) => c.id === categoryId)) setCategoryId(available[0]?.id || null); }, [categories, view, categoryId]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3500); return () => window.clearTimeout(timer); }, [toast]);

  const labels = copy[language];
  const filteredCategories = categories.filter((category) => category.kind === view);
  const visibleItems = items.filter((item) => item.categoryId === categoryId);
  const total = useMemo(() => cartTotal(cart), [cart]);
  const totalQuantity = cart.reduce((sum, line) => sum + line.quantity, 0);

  function addToCart(item: MenuItem, quantity: number, note: string) {
    setCart((current) => {
      const index = current.findIndex((line) => line.item.id === item.id && line.note === note);
      if (index === -1) return [...current, { item, quantity, note }];
      return current.map((line, i) => i === index ? { ...line, quantity: Math.min(20, line.quantity + quantity) } : line);
    });
    setSelected(null); setToast(`${text(item.name, language)} ${language === "am" ? "ወደ ትዕዛዝ ተጨምሯል" : "added to your order"}`);
  }

  function updateLine(index: number, quantity: number) { setCart((current) => quantity <= 0 ? current.filter((_, i) => i !== index) : current.map((line, i) => i === index ? { ...line, quantity } : line)); }

  return <main className="paper-grain min-h-screen pb-28">
    <header className="sticky top-0 z-30 border-b border-[var(--line)] bg-[rgba(248,241,228,.93)] backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><BrandMark /><div className="flex items-center gap-3"><div className="hidden text-right text-xs text-[var(--muted)] sm:block"><span className="block font-semibold text-[var(--ink)]">{labels.table} {table.label}</span><span>Secure table menu</span></div><LanguageToggle language={language} onChange={setLanguage} /></div></div></header>

    <section className="mx-auto max-w-6xl px-4 pt-8 sm:px-6 sm:pt-12"><div className="overflow-hidden rounded-3xl bg-[var(--forest)] px-6 py-8 text-[#fff9ed] sm:px-10 sm:py-12"><p className="eyebrow text-[#e8bb63]">{labels.table} · {table.label}</p><h1 className="font-display mt-3 max-w-xl text-4xl leading-none tracking-tight sm:text-6xl">{language === "am" ? "እንኳን ወደ ፋንትሽ በደህና መጡ" : "Welcome to the Fantish table."}</h1><p className="mt-5 max-w-lg text-sm leading-6 text-[#e9ddcf] sm:text-base">{language === "am" ? "የተመረጡ የኢትዮጵያ ጣዕሞች፣ በጥንቃቄ ለእርስዎ የተዘጋጁ።" : "A considered selection of Ethiopian flavors, prepared with warmth for your table."}</p></div></section>

    <nav aria-label="Menu sections" className="mx-auto mt-7 flex max-w-6xl gap-2 overflow-x-auto px-4 pb-2 sm:px-6"><SectionButton current={view} target="food" label={labels.food} setView={setView} /><SectionButton current={view} target="drink" label={labels.drinks} setView={setView} /><SectionButton current={view} target="lounge" label={labels.lounge} setView={setView} /></nav>

    {view === "lounge" ? <Lounge services={services} language={language} onRequest={setService} /> : <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="flex gap-2 overflow-x-auto pb-5">{filteredCategories.map((category) => <button key={category.id} onClick={() => setCategoryId(category.id)} className={`focus-ring shrink-0 rounded-full border px-4 py-2 text-sm font-bold ${categoryId === category.id ? "border-[var(--terracotta)] bg-[var(--terracotta)] text-white" : "border-[var(--line)] bg-white text-[var(--ink)]"}`}>{text(category.name, language)}</button>)}</div><div className="mb-6"><p className="eyebrow text-[var(--terracotta)]">{categoryId ? text(categories.find((c) => c.id === categoryId)?.description || { en: "", am: "" }, language) : ""}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visibleItems.map((item) => <MenuCard key={item.id} item={item} language={language} onSelect={setSelected} />)}</div></section>}

    {totalQuantity > 0 && <button onClick={() => setCartOpen(true)} className="focus-ring fixed inset-x-4 bottom-4 z-30 mx-auto flex max-w-xl items-center justify-between rounded-2xl bg-[var(--terracotta)] px-5 py-4 text-left text-white shadow-[0_12px_30px_rgba(95,31,17,.35)]"><span><strong className="block text-sm">{labels.viewCart}</strong><span className="text-xs text-white/80">{totalQuantity} {totalQuantity === 1 ? "item" : "items"}</span></span><strong>{formatETB(total)}</strong></button>}
    {selected && <DetailModal item={selected} language={language} onClose={() => setSelected(null)} onAdd={addToCart} />}
    {cartOpen && <CartSheet table={table} cart={cart} language={language} total={total} onClose={() => setCartOpen(false)} onUpdate={updateLine} onSuccess={() => window.localStorage.removeItem(storageKey)} />}
    {service && <ServiceRequest service={service} table={table} language={language} onClose={() => setService(null)} onDone={() => { setService(null); setToast(language === "am" ? "ጥያቄዎ ተልኳል" : "Your request is with our team." ); }} />}
    {toast && <div role="status" className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[var(--ink)] px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}
  </main>;
}

function SectionButton({ current, target, label, setView }: { current: View; target: View; label: string; setView: (view: View) => void }) { return <button onClick={() => setView(target)} className={`focus-ring shrink-0 rounded-full px-5 py-2.5 text-sm font-bold ${current === target ? "bg-[var(--ink)] text-white" : "border border-[var(--line)] bg-white"}`}>{label}</button>; }

function MenuCard({ item, language, onSelect }: { item: MenuItem; language: Language; onSelect: (item: MenuItem) => void }) {
  const image = item.images[0];
  return <button onClick={() => onSelect(item)} className="focus-ring group overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--cream)] text-left transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative aspect-[1.25] overflow-hidden bg-[#dec8a7]">{image && <Image src={image.url} alt={text(image.alt, language)} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" />}{item.isFeatured && <span className="absolute left-3 top-3 rounded-full bg-[var(--gold)] px-2.5 py-1 text-[.65rem] font-bold uppercase tracking-wide text-[var(--ink)]">Signature</span>}</div><div className="p-4"><div className="flex justify-between gap-3"><h2 className="font-display text-xl leading-tight">{text(item.name, language)}</h2><strong className="shrink-0 text-sm">{formatETB(item.priceEtb)}</strong></div><p className="mt-2 line-clamp-2 text-sm leading-5 text-[var(--muted)]">{text(item.description, language)}</p><span className="mt-4 inline-block text-xs font-bold text-[var(--terracotta)]">{language === "am" ? "ዝርዝር ይመልከቱ" : "View details"} →</span></div></button>;
}

function DetailModal({ item, language, onClose, onAdd }: { item: MenuItem; language: Language; onClose: () => void; onAdd: (item: MenuItem, quantity: number, note: string) => void }) {
  const [imageIndex, setImageIndex] = useState(0); const [quantity, setQuantity] = useState(1); const [note, setNote] = useState(""); const labels = copy[language]; const image = item.images[imageIndex];
  return <div className="fixed inset-0 z-40 overflow-y-auto bg-[rgba(35,20,13,.58)] p-3 sm:p-8" role="dialog" aria-modal="true" aria-label={text(item.name, language)}><div className="mx-auto max-w-3xl overflow-hidden rounded-3xl bg-[var(--cream)] shadow-2xl"><div className="relative aspect-[1.35] bg-[#ddc39c]">{image && <Image src={image.url} alt={text(image.alt, language)} fill className="object-cover" sizes="(max-width: 768px) 100vw, 768px" />}<button onClick={onClose} aria-label="Close item details" className="focus-ring absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white text-xl shadow">×</button>{item.images.length > 1 && <div className="absolute inset-x-4 bottom-4 flex gap-2">{item.images.map((entry, index) => <button key={entry.id} onClick={() => setImageIndex(index)} aria-label={`Show photo ${index + 1}`} className={`h-2.5 flex-1 rounded-full ${index === imageIndex ? "bg-white" : "bg-white/50"}`} />)}</div>}</div><div className="p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-[var(--terracotta)]">Fantish kitchen</p><h2 className="font-display mt-2 text-3xl leading-none">{text(item.name, language)}</h2></div><strong className="rounded-full bg-[var(--gold)] px-4 py-2 text-sm">{formatETB(item.priceEtb)}</strong></div><p className="mt-5 leading-7 text-[var(--muted)]">{text(item.description, language)}</p><div className="mt-6 grid gap-3 rounded-2xl bg-[#f2e6d2] p-4 sm:grid-cols-2"><div><p className="eyebrow text-[var(--terracotta)]">{language === "am" ? "ግብዓቶች" : "Ingredients"}</p><p className="mt-2 text-sm leading-6">{text(item.ingredients, language)}</p></div><div><p className="eyebrow text-[var(--terracotta)]">{language === "am" ? "የባህል ማስታወሻ" : "Cultural note"}</p><p className="mt-2 text-sm leading-6">{text(item.culturalNote, language)}</p></div></div><label className="mt-6 block text-sm font-bold">{labels.note}<textarea value={note} onChange={(event) => setNote(event.target.value.slice(0, 280))} placeholder={language === "am" ? "ምሳሌ፡ በትንሽ ቅመም" : "e.g. lightly spiced, no onion"} className="focus-ring mt-2 min-h-20 w-full rounded-xl border border-[var(--line)] bg-white p-3 text-sm font-normal" /></label><div className="mt-6 flex items-center justify-between gap-4"><QuantityControl quantity={quantity} setQuantity={setQuantity} /><button onClick={() => onAdd(item, quantity, note.trim())} className="focus-ring flex-1 rounded-full bg-[var(--terracotta)] px-5 py-3 text-sm font-bold text-white hover:bg-[var(--terracotta-deep)]">{labels.add} · {formatETB(item.priceEtb * quantity)}</button></div></div></div></div>;
}

function CartSheet({ table, cart, language, total, onClose, onUpdate, onSuccess }: { table: TableInfo; cart: CartLine[]; language: Language; total: number; onClose: () => void; onUpdate: (index: number, quantity: number) => void; onSuccess: () => void }) {
  const [guestNote, setGuestNote] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const labels = copy[language];
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { const response = await fetch("/api/orders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tableToken: table.token, guestNote: guestNote.slice(0, 500), idempotencyKey: crypto.randomUUID(), items: cart.map((line) => ({ menuItemId: line.item.id, quantity: line.quantity, note: line.note })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to place order."); onSuccess(); window.location.assign(`/order/${data.trackingToken}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to place order. Your cart is still here—please try again."); setPending(false); } }
  return <div className="fixed inset-0 z-40 bg-[rgba(35,20,13,.58)]" role="dialog" aria-modal="true" aria-label={labels.cart}><form onSubmit={submit} className="absolute inset-x-0 bottom-0 mx-auto max-h-[92svh] max-w-xl overflow-y-auto rounded-t-3xl bg-[var(--cream)] p-5 shadow-2xl sm:bottom-5 sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="eyebrow text-[var(--terracotta)]">{labels.table} · {table.label}</p><h2 className="font-display mt-1 text-3xl">{labels.cart}</h2></div><button type="button" onClick={onClose} className="focus-ring grid h-9 w-9 place-items-center rounded-full border border-[var(--line)] text-xl">×</button></div>{cart.length === 0 ? <p className="py-10 text-center text-[var(--muted)]">{labels.emptyCart}</p> : <><div className="my-5 divide-y divide-[var(--line)]">{cart.map((line, index) => <div key={`${line.item.id}-${line.note}-${index}`} className="flex items-center justify-between gap-3 py-4"><div><h3 className="font-display text-lg">{text(line.item.name, language)}</h3>{line.note && <p className="mt-1 text-xs text-[var(--muted)]">{line.note}</p>}<p className="mt-1 text-sm font-bold">{formatETB(line.item.priceEtb * line.quantity)}</p></div><div className="flex items-center rounded-full border border-[var(--line)] bg-white"><button type="button" className="focus-ring h-8 w-8" onClick={() => onUpdate(index, line.quantity - 1)}>−</button><span className="w-6 text-center text-sm font-bold">{line.quantity}</span><button type="button" className="focus-ring h-8 w-8" onClick={() => onUpdate(index, line.quantity + 1)}>+</button></div></div>)}</div><p className="rounded-xl border border-[#e4c58b] bg-[#fff4df] p-3 text-xs leading-5 text-[var(--muted)]">{labels.allergy}</p><label className="mt-4 block text-sm font-bold">{language === "am" ? "የትዕዛዝ ማስታወሻ" : "Order note"}<textarea value={guestNote} onChange={(event) => setGuestNote(event.target.value)} className="focus-ring mt-2 min-h-20 w-full rounded-xl border border-[var(--line)] bg-white p-3 text-sm font-normal" placeholder={language === "am" ? "ለቡድናችን ሌላ ማስታወሻ" : "Anything else our team should know?"} /></label><div className="mt-5 flex items-center justify-between border-t border-[var(--line)] pt-4"><span className="font-display text-xl">{labels.total}</span><strong className="text-xl">{formatETB(total)}</strong></div>{error && <p role="alert" className="mt-3 rounded-lg bg-[#f9dcd4] p-3 text-sm text-[#7f2919]">{error}</p>}<button disabled={pending} className="focus-ring mt-5 w-full rounded-full bg-[var(--terracotta)] px-5 py-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{pending ? (language === "am" ? "በመላክ ላይ..." : "Sending to kitchen...") : `${labels.placeOrder} · ${formatETB(total)}`}</button><p className="mt-3 text-center text-xs text-[var(--muted)]">{language === "am" ? "ክፍያ ከአስተናጋጅ ጋር ይፈጸማል።" : "Payment is settled with your server or cashier."}</p></>}</form></div>;
}

function Lounge({ services, language, onRequest }: { services: HotelService[]; language: Language; onRequest: (service: HotelService) => void }) { return <section id="lounge" className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="mb-7 max-w-xl"><p className="eyebrow text-[var(--terracotta)]">Hotel & Lounge</p><h2 className="font-display mt-2 text-4xl leading-none">{language === "am" ? "ከማዕድ በላይ" : "Beyond the table."}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{language === "am" ? "የፋንትሽ እንግዳ አቀባበልን በላውንጅ እና በሆቴል ያግኙ።" : "Discover Fantish hospitality in our lounge and throughout the hotel."}</p></div><div className="grid gap-5 sm:grid-cols-2">{services.map((entry) => <article key={entry.id} className="overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--cream)]"><div className="relative aspect-[1.6]"><Image src={entry.imageUrl} alt={text(entry.title, language)} fill className="object-cover" sizes="(max-width: 640px) 100vw, 50vw" /></div><div className="p-5"><h3 className="font-display text-2xl">{text(entry.title, language)}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text(entry.description, language)}</p><button onClick={() => onRequest(entry)} className="focus-ring mt-5 rounded-full bg-[var(--forest)] px-4 py-2.5 text-sm font-bold text-white">{text(entry.requestLabel, language)}</button></div></article>)}</div></section>; }

function ServiceRequest({ service, table, language, onClose, onDone }: { service: HotelService; table: TableInfo; language: Language; onClose: () => void; onDone: () => void }) { const [note, setNote] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); async function send(event: FormEvent) { event.preventDefault(); setPending(true); const response = await fetch("/api/service-requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tableToken: table.token, serviceId: service.id, note: note.slice(0, 500) }) }); if (response.ok) onDone(); else { const data = await response.json(); setError(data.error || "Unable to send request."); setPending(false); } } return <div className="fixed inset-0 z-40 grid place-items-end bg-[rgba(35,20,13,.58)] p-3 sm:place-items-center" role="dialog" aria-modal="true"><form onSubmit={send} className="w-full max-w-md rounded-3xl bg-[var(--cream)] p-6"><div className="flex justify-between gap-4"><div><p className="eyebrow text-[var(--terracotta)]">{table.label}</p><h2 className="font-display mt-1 text-3xl">{text(service.title, language)}</h2></div><button type="button" onClick={onClose} className="focus-ring h-9 w-9 rounded-full border border-[var(--line)] text-xl">×</button></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{text(service.description, language)}</p><textarea value={note} onChange={(event) => setNote(event.target.value)} className="focus-ring mt-5 min-h-24 w-full rounded-xl border border-[var(--line)] bg-white p-3 text-sm" placeholder={language === "am" ? "ጥያቄዎን ይጻፉ" : "Tell us how we can help"} />{error && <p role="alert" className="mt-3 text-sm text-[var(--terracotta)]">{error}</p>}<button disabled={pending} className="focus-ring mt-5 w-full rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending ? "…" : text(service.requestLabel, language)}</button></form></div>; }
