"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { StaffGate, StaffHeader } from "@/components/StaffGate";
import type { StaffRole } from "@/lib/types";

type TableRow = { id: string; label: string; qr_token: string; is_active: boolean };

export default function StaffTablesPage() { return <StaffGate administratorOnly>{(client, role) => <TableManager client={client} role={role} />}</StaffGate>; }

function TableManager({ client, role }: { client: SupabaseClient; role: StaffRole }) {
  const [tables, setTables] = useState<TableRow[]>([]); const [message, setMessage] = useState(""); const [siteUrl, setSiteUrl] = useState("");
  const refresh = useCallback(async () => { const { data, error } = await client.from("restaurant_tables").select("id,label,qr_token,is_active").order("label"); if (error) setMessage("Tables could not be loaded."); else setTables((data || []) as TableRow[]); }, [client]);
  useEffect(() => { setSiteUrl(window.location.origin); refresh(); }, [refresh]);
  async function addTable(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const label = String(form.get("label") || "").trim(); if (!label) return; const { error } = await client.from("restaurant_tables").insert({ label }); setMessage(error ? "A table with that label already exists." : "Table created. Download its QR card below."); if (!error) { event.currentTarget.reset(); refresh(); } }
  async function rotate(table: TableRow) { if (!window.confirm(`Rotate the QR code for ${table.label}? Existing printed codes will stop working.`)) return; const { error } = await client.from("restaurant_tables").update({ qr_token: crypto.randomUUID() }).eq("id", table.id); setMessage(error ? "QR code could not be rotated." : `QR code rotated for ${table.label}. Reprint its card.`); refresh(); }
  async function downloadQr(table: TableRow) { try { const QRCode = await import("qrcode"); const url = `${siteUrl}/table/${table.qr_token}`; const dataUrl = await QRCode.toDataURL(url, { width: 900, margin: 2, color: { dark: "#251812", light: "#fffaf1" } }); const printable = window.open("", "_blank"); if (!printable) throw new Error("Popup blocked"); printable.document.write(`<title>Fantish ${table.label} QR</title><style>body{font-family:Georgia,serif;text-align:center;padding:36px;color:#251812}img{width:280px;height:280px}small{font-family:Arial}h1{font-size:32px;margin:0}p{font-size:17px}</style><h1>Fantish</h1><p>ፋንትሽ ቁርጥ እና ክትፎ</p><h2>${table.label}</h2><img src="${dataUrl}" alt="QR code for ${table.label}"/><p>Scan to view the table menu</p><small>${url}</small><script>window.print()</script>`); printable.document.close(); } catch { setMessage("QR card could not be created. Please allow popups and try again."); } }
  async function toggle(table: TableRow) { const { error } = await client.from("restaurant_tables").update({ is_active: !table.is_active }).eq("id", table.id); setMessage(error ? "Table status could not be changed." : `${table.label} is now ${table.is_active ? "inactive" : "active"}.`); refresh(); }
  return <main className="min-h-screen bg-[#eee5d9]"><StaffHeader role={role} /><section className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><p className="eyebrow text-[var(--terracotta)]">Administrator</p><h1 className="font-display mt-2 text-4xl leading-none">Table QR codes</h1><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">Every code contains a private table token. Rotate a token if a printed card is lost or a table is moved, then print a fresh QR card.</p>{message && <p className="mt-5 rounded-xl bg-[#fff0d6] p-3 text-sm text-[var(--terracotta-deep)]">{message}</p>}<form onSubmit={addTable} className="mt-8 flex max-w-lg flex-wrap gap-3 rounded-2xl bg-white p-4 shadow-sm"><input required name="label" placeholder="e.g. Garden 05" className="focus-ring min-w-44 flex-1 rounded-xl border border-[var(--line)] px-3 py-2.5 text-sm" /><button className="focus-ring rounded-full bg-[var(--ink)] px-5 py-2.5 text-sm font-bold text-white">Add table</button></form><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tables.map((table) => <article key={table.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><p className="eyebrow text-[var(--terracotta)]">Table</p><h2 className="font-display mt-1 text-2xl">{table.label}</h2></div><span className={`h-fit rounded-full px-2.5 py-1 text-[.65rem] font-bold uppercase ${table.is_active ? "bg-[#dceee3] text-[#1c6542]" : "bg-[#e4dfd7] text-[#6c6058]"}`}>{table.is_active ? "Active" : "Inactive"}</span></div><p className="mt-4 break-all font-mono text-[.65rem] text-[var(--muted)]">{table.qr_token}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => downloadQr(table)} className="focus-ring rounded-full bg-[var(--terracotta)] px-3 py-2 text-xs font-bold text-white">Print QR</button><button onClick={() => rotate(table)} className="focus-ring rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold">Rotate</button><button onClick={() => toggle(table)} className="focus-ring rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold">{table.is_active ? "Deactivate" : "Activate"}</button></div></article>)}</div></section></main>;
}
